### PR TITLE
Allow arbitrary editing of json in captions studio

### PR DESCRIPTION
**Pull request by BernsteinA**
- changed json preview `mode` from "form" to "text" (see https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#configuration-options)
- changed callback from `onChangeJSON` to `onChangeText`
- support adding captions from json, not just editing existing captions

### CODE REVIEW

**Comment by 902seanryan** [comment]
@BernsteinA it looks like switching over to `text` breaks the validation when editing the caption JSON directly. If you edit the text its either not validating properly, or the JSON object might not be the same format. 

We might need to tweak the validation steps a bit to work with the text format. 

Screen Shot 2021-07-20 at 10 51 09 AM

Screen Shot 2021-07-20 at 10 55 28 AM

**Comment by BernsteinA** [comment]
Strange, validation is working in my local build.
Anyway, I don't think the function to Open Caption File existed when I made this fork, so this PR may not be as useful as I thought it was. Maybe I could add a button to toggle between the two json views

**Comment by 902seanryan** [comment]
> Strange, validation is working in my local build.
> Anyway, I don't think the function to Open Caption File existed when I made this fork, so this PR may not be as useful as I thought it was. Maybe I could add a button to toggle between the two json views

Oh its possible I broke something when I was playing around, I'll try square one just to see. But yeah if the fork wasn't off the most recent version (as of 1.0.0 release) then it could be missing. You can import JSON files as a whole, or you could always edit the actual JSON file in a text editor and next load the studio will pick it up. 

So maybe we could look into doing the toggle between views or maybe a refresh button when editing the text file directly?
@deycorinne any thoughts?

**Comment by deycorinne** [comment]
> > Strange, validation is working in my local build.
> > Anyway, I don't think the function to Open Caption File existed when I made this fork, so this PR may not be as useful as I thought it was. Maybe I could add a button to toggle between the two json views
> 
> Oh its possible I broke something when I was playing around, I'll try square one just to see. But yeah if the fork wasn't off the most recent version (as of 1.0.0 release) then it could be missing. You can import JSON files as a whole, or you could always edit the actual JSON file in a text editor and next load the studio will pick it up.
> 
> So maybe we could look into doing the toggle between views or maybe a refresh button when editing the text file directly?
> @deycorinne any thoughts?

I think a refresh button sounds like a good solution! We should ticket it out in pivotal and chat about it in our next meeting

**Comment by 902seanryan** [comment]
Sounds good, @BernsteinA in the meantime if you were to edit the JSON file directly and re-import it or exit caption studio and re-open it it'll catch the changes (it should at least).

**Comment by 902seanryan** [comment]
@BernsteinA Turns out the JSON editor supports switching between the two modes rather elegantly by default. We'll be releasing an updated version shortly that supports both. I'm just doing some additional testing.

As such I'm going to close this PR. I'll make sure to let you know when its ready!

**Comment by 902seanryan** [comment]
@BernsteinA Sorry I didn't know how else to get back to you. But version 1.1.0 of Studio is now out and supports switching between the `code` and `form` modes! If you have the chance to try it out let us know how it works for you.

**Pull request closed without merging**
